### ISSUE TITLE
Error Cannot read property 'x' of null when candidates contain hidden elements

### ISSUE THREAD

**Issue by jannikb** [jfgreffier/playwright-relative-selector#34]
`ElementHandle<T>.boundingBox()` returns null if an element is hidden. So if the candidate selector matches a hidden element the following error is thrown:
```
TypeError: Cannot read property 'x' of null
    at toLeftOf (node_modules/playwright-relative-selector/src/logic.js:10:24)
    at meetsProximitySelector (node_modules/playwright-relative-selector/src/index.js:33:10)
    at relativeSelector (node_modules/playwright-relative-selector/src/index.js:63:13)
    at Context.<anonymous> (test/integration/test.ts:27:9)
``` 
To reproduce the issue:
```js
await page.setContent('<a>visible</a><span>myText</span><a style="display: none">hidden</a>');
await relativeSelector(page, 'css=a toLeftOf text="myText"');
```

**Comment by jfgreffier** [comment]
Yes, that's an actual issue. I suppose it should return `null` and don't throw exception in the way Playwright handles it when selector matches nothing.

I'll check it

**Comment by jfgreffier** [comment]
This tool is now deprecated.
